[package]
description = "A port of Mojang's Authlib and launcher authentication."
edition = "2021"
license = "MIT"
name = "azalea-auth"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-auth"
version = "0.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azalea-buf = { path = "../azalea-buf", version = "^0.6.0" }
azalea-crypto = { path = "../azalea-crypto", version = "^0.6.0" }
chrono = { version = "0.4.26", default-features = false }
log = "0.4.20"
num-bigint = "0.4.4"
reqwest = { version = "0.11.20", default-features = false, features = [
    "json",
    "rustls-tls",
] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["fs"] }
uuid = { version = "^1.4.1", features = ["serde"] }

[dev-dependencies]
env_logger = "0.9.3"
tokio = { version = "1.32.0", features = ["full"] }
