[package]
description = "A port of Mojang's Brigadier command parsing and dispatching library."
edition = "2021"
license = "MIT"
name = "azalea-brigadier"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
