[package]
description = "A framework for creating Minecraft bots."
edition = "2021"
license = "MIT"
name = "azalea"
repository = "https://github.com/azalea-rs/azalea/tree/main/azalea"
version = "0.9.0"

[package.metadata.release]
pre-release-replacements = [
  { file = "README.md", search = "`azalea = \"[a-z0-9\\.-]+\"`", replace = "`azalea = \"{{version}}\"`" },
]

[dependencies]
anyhow = "^1.0.79"
async-trait = "0.1.77"
azalea-block = { version = "0.9.0", path = "../azalea-block" }
azalea-chat = { version = "0.9.0", path = "../azalea-chat" }
azalea-client = { version = "0.9.0", path = "../azalea-client", default-features = false }
azalea-core = { version = "0.9.0", path = "../azalea-core" }
azalea-inventory = { version = "0.9.0", path = "../azalea-inventory" }
azalea-physics = { version = "0.9.0", path = "../azalea-physics" }
azalea-protocol = { version = "0.9.0", path = "../azalea-protocol" }
azalea-registry = { version = "0.9.0", path = "../azalea-registry" }
azalea-world = { version = "0.9.0", path = "../azalea-world" }
azalea-auth = { version = "0.9.0", path = "../azalea-auth" }
azalea-brigadier = { version = "0.9.0", path = "../azalea-brigadier" }
azalea-buf = { version = "0.9.0", path = "../azalea-buf" }
bevy_app = "0.13.0"
bevy_ecs = "0.13.0"
bevy_tasks = { version = "0.13.0", features = ["multi-threaded"] }
derive_more = { version = "0.99.17", features = ["deref", "deref_mut"] }
futures = "0.3.30"
futures-lite = "2.2.0"
tracing = "0.1.40"
nohash-hasher = "0.2.0"
num-traits = "0.2.18"
parking_lot = { version = "^0.12.1", features = ["deadlock_detection"] }
priority-queue = "1.4.0"
thiserror = "^1.0.57"
tokio = "^1.36.0"
uuid = "1.7.0"
bevy_log = "0.13.0"
azalea-entity = { version = "0.9.0", path = "../azalea-entity" }
bevy_time = "0.13.0"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[features]
default = ["log"]
# enables bevy_log::LogPlugin by default
log = ["azalea-client/log"]

[[bench]]
name = "pathfinder"
harness = false

[[bench]]
name = "physics"
harness = false
