[package]
description = "Cryptography features used in Minecraft."
edition = "2021"
license = "MIT"
name = "azalea-crypto"
version = "0.6.0"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-crypto"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.3"
azalea-buf = {path = "../azalea-buf", version = "^0.6.0" }
cfb8 = "0.8.1"
num-bigint = "^0.4.4"
rand = {version = "^0.8.5", features = ["getrandom"]}
rsa_public_encrypt_pkcs1 = "0.4.0"
sha-1 = "^0.10.1"
uuid = "^1.4.1"

[dev-dependencies]
criterion = {version = "^0.4.0", features = ["html_reports"]}

[[bench]]
harness = false
name = "my_benchmark"
