[package]
description = "A headless Minecraft client."
edition = "2021"
license = "MIT"
name = "azalea-client"
repository = "https://github.com/mat-1/azalea/tree/main/azalea-client"
version = "0.6.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
azalea-auth = { path = "../azalea-auth", version = "0.6.0" }
azalea-block = { path = "../azalea-block", version = "0.6.0" }
azalea-chat = { path = "../azalea-chat", version = "0.6.0" }
azalea-core = { path = "../azalea-core", version = "0.6.0" }
azalea-crypto = { path = "../azalea-crypto", version = "0.6.0" }
azalea-physics = { path = "../azalea-physics", version = "0.6.0" }
azalea-protocol = { path = "../azalea-protocol", version = "0.6.0" }
azalea-registry = { path = "../azalea-registry", version = "0.6.0" }
azalea-world = { path = "../azalea-world", version = "0.6.0" }
bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
bevy_log = "0.10.1"
bevy_tasks = "0.10.1"
bevy_time = "0.10.1"
derive_more = { version = "0.99.17", features = ["deref", "deref_mut"] }
futures = "0.3.28"
log = "0.4.20"
nohash-hasher = "0.2.0"
once_cell = "1.18.0"
parking_lot = { version = "^0.12.1", features = ["deadlock_detection"] }
regex = "1.9.4"
thiserror = "^1.0.47"
tokio = { version = "^1.32.0", features = ["sync"] }
typemap_rev = "0.3.0"
uuid = "^1.4.1"
